name:                kata
version:             0.1.0.0
github:              "mark-gerarts/kata"
license:             BSD3
author:              "Mark Gerarts"
maintainer:          "mark.gerarts@gmail.com"
copyright:           "2018 Mark Gerarts"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mark-gerarts/kata#readme>

dependencies:
- base >= 4.7 && < 5
- hspec >= 2.5 && < 3.0

library:
  source-dirs: src

executables:
  kata-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kata

tests:
  kata-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kata
